const payloadFactory = require('../helpers/payloadFactory.js');

const perform = async (z, bundle) => {
  // z.console.log("bundle:", JSON.stringify(bundle, null, 2));
  const body = payloadFactory(bundle.inputData);

  const options = {
    url: `${process.env.YOJEE_API_URL}/api/v3/dispatcher/orders`,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      access_token: bundle.authData.access_token,
      company_slug: bundle.authData.company_slug,
    },
    params: {},
    body: body,
  };

  z.console.log("options:", JSON.stringify(options, null, 2));

  // return {};
  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;
    z.console.log("results:", JSON.stringify(results, null, 2));
    // You can do any parsing you need for results here before returning them

    return results;
  });
};

module.exports = {
  operation: {
    perform: perform,
    sample: {
      data: {
        cancelled_at: null,
        container_no: null,
        display_price: 'SGD 0',
        external_id: 'TEST-ORDER-001',
        id: 410013,
        inserted_at: '2021-07-25T11:13:01.524025Z',
        number: 'O-QTROJOUMTNM8',
        order_items: [
          { cod_price: null, id: 434791, tracking_number: 'YOJ-4UABMDSOJ2VD' },
        ],
        paid: false,
        placed_by_user_profile_id: 5929,
        price: { amount: '0', currency: 'SGD' },
        sender_id: 1750,
        status: 'created',
      },
      message: 'Created the order.',
      warning: false,
    },
    outputFields: [
      { key: 'data__cancelled_at' },
      { key: 'data__container_no' },
      { key: 'data__display_price' },
      { key: 'data__external_id' },
      { key: 'data__id' },
      { key: 'data__inserted_at' },
      { key: 'data__number' },
      { key: 'data__order_items[]cod_price' },
      { key: 'data__order_items[]id' },
      { key: 'data__order_items[]tracking_number' },
      { key: 'data__paid' },
      { key: 'data__placed_by_user_profile_id' },
      { key: 'data__price__amount' },
      { key: 'data__price__currency' },
      { key: 'data__sender_id' },
      { key: 'data__status' },
      { key: 'message' },
      { key: 'warning' },
    ],
    inputFields: [
      {
        key: 'external_order_id',
        label: 'External Order ID',
        type: 'string',
        helpText: 'Unique reference ID in your system',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'sender_id',
        label: 'Sender ID',
        type: 'integer',
        helpText:
          "The numeric ID of the Sender in Yojee's system. Either Sender ID or Sender External ID is needed to create an order",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'external_sender_id',
        label: 'External Sender ID',
        type: 'string',
        helpText:
          "The string that uniquely identifies a Sender in Yojee's system. Either Sender ID or Sender External ID is needed to create an order",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'order_price_amount',
        label: 'Order Price Amount',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'order_currency',
        label: 'Order Currency',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_address',
        label: 'Pickup Address Line 1',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_address2',
        label: 'Pickup Address Line 2',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_country',
        label: 'Pickup Country',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_state',
        label: 'Pickup State',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_postal_code',
        label: 'Pickup Postal Code',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_contact_company',
        label: 'Pickup Contact Company',
        type: 'string',
        helpText: 'Company of the contact person at pickup',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_contact_name',
        label: 'Pickup Contact Name',
        type: 'string',
        helpText: 'Name of the contact person at pickup',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_contact_phone',
        label: 'Pickup Contact Phone',
        type: 'string',
        helpText:
          'The phone number if SMS notification is required. The corresponding notification setting also needs to be enabled in Yojee.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_contact_email',
        label: 'Pickup Contact Email',
        type: 'string',
        helpText:
          'The email address if email notification is required. The corresponding notification setting also needs to be enabled in Yojee',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_from_time',
        label: 'Pickup From Time',
        type: 'string',
        helpText:
          'Start of time slot for this step in ISO8601 format. Example: 2021-08-03T08:59:22.813Z. If this field is empty, we will default to current time plus 1 day.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'pickup_to_time',
        label: 'Pickup To Time',
        type: 'string',
        helpText:
          'End of time slot for this step in ISO8601 format. Example: 2021-08-04T07:59:59.813Z. If this field is empty, we will default to current time plus 2 days.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_address',
        label: 'Dropoff Address Line 1',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_address2',
        label: 'Dropoff Address Line 2',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_country',
        label: 'Dropoff Country',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_state',
        label: 'Dropoff State',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_postal_code',
        label: 'Dropoff Postal Code',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_contact_company',
        label: 'Dropoff Contact Company',
        type: 'string',
        helpText: 'Company of the contact person at dropoff',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_contact_name',
        label: 'Dropoff Contact Name',
        type: 'string',
        helpText: 'Name of the contact person at dropoff',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_contact_phone',
        label: 'Dropoff Contact Phone',
        type: 'string',
        helpText:
          'The phone number if SMS notification is required. The corresponding notification setting also needs to be enabled in Yojee.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_contact_email',
        label: 'Dropoff Contact Email',
        type: 'string',
        helpText:
          'The email address if email notification is required. The corresponding notification setting also needs to be enabled in Yojee',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_from_time',
        label: 'Dropoff From Time',
        type: 'string',
        helpText:
          'Start of time slot for this step in ISO8601 format. Example: 2021-08-03T08:59:22.813Z. If this field is empty, we will default to current time plus 1 day.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'dropoff_to_time',
        label: 'Dropoff To Time',
        type: 'string',
        helpText:
          'End of time slot for this step in ISO8601 format. Example: 2021-08-04T07:59:59.813Z. If this field is empty, we will default to current time plus 2 days.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'items',
        children: [
          {
            key: 'item_description',
            label: 'Description',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_width',
            label: 'Width',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_length',
            label: 'Length',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_height',
            label: 'Height',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_weight',
            label: 'Weight',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_quantity',
            label: 'Quantity',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_info',
            label: 'Information',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_external_customer_id',
            label: 'Additional Reference Number 1',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_external_customer_id2',
            label: 'Additional Reference Number 2',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_external_customer_id3',
            label: 'Additional Reference Number 3',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_payload_type',
            label: 'Item Type',
            type: 'string',
            helpText: 'Item Type defined in Yojee Dispatcher',
            required: true,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_price_info',
            label: 'Price Info',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_service_type',
            label: 'Service Type',
            type: 'string',
            helpText: 'Service Type defined in Yojee Dispatcher',
            required: true,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_volume',
            label: 'Volume',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_volumetric_weight',
            label: 'Volumetric Weight',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'item_price_amount',
            label: 'Price Amount',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
        ],
        label: 'Items',
        required: false,
        altersDynamicFields: false,
      },
    ],
  },
  key: 'create_simple_order',
  noun: 'Order',
  display: {
    label: 'Create Simple Order',
    description:
      'Create a simple Yojee Order with one Pickup location and one Dropoff location for 1 item',
    hidden: false,
    important: true,
  },
};
